name: Deploy Preview to GitHub Pages

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
        USER_NAME: thhomas
        USER_EMAIL: thomas.tilak@gmail.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-preview

      - name: Deploy to GitHub Pages
        run: |
         git config --global user.name $USER_NAME
         git config --global user.email $USER_EMAIL
         git remote set-url origin https://$USER_NAME:${{ secrets.GH_SECRET }}@github.com/PacificCommunity/sdmx-dashboard-components.git
         npm run publish
